### ISSUE TITLE
Rails 3?

### ISSUE THREAD

**Issue by zapnap** [bkoski/slug#1]
This seems to work just fine in Rails 3. However, there are a few deprecation warnings due to the use of before_validation_on_create.

I'm happy to provide a patch but I wasn't sure what the status of this project is. I assume the goal is to remain both Rails 2.x and Rails 3.x compatible?

**Comment by bkoski** [comment]
This is now fixed thanks to 20a6987417dd278de0f379b409fb68180170a858!
